apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GtA432mJLlrNUujkRikgzdMJWh7BLFXDrrRvfkSbsd5+TsVK,iv:t/fE+M1P0CGXDe9Pm11VZf/EN+odyLS/HoCIxdCrQpI=,tag:kHA141jhhhdfw5HJhaNZhw==,type:str]
    credentials.json: ENC[AES256_GCM,data:qz3+Il6mmfeduAGTZNFIGAjBO0K5fE+3DtaKp1Lvm6mtp7Z+ytX2jknQK8NuzZ9782S3yr7ZNDKHnQgjqr1E0ljlHPU4hVcr5za+ExbZ3CKbhisXNF/hntko1uFNcqzD9Hbi2kfKgICz2N92ql39z/R9G+V/J9j+gv72uucjoB+wkL8XTq1zR/dkucKpjAutNYvGCl7a1sQdRUow9PxzplnUtdmiOM5MR79QbyR8Bw==,iv:JNjskcCfa4Qo7+ouIanBpfg8hs+WvYH9yxrQGoDWdBs=,tag:ha/i70lp0gEsPWrv+HqJiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t60uwv0pgk7fnsvn6g0wjrp2hpjsskcqlkgysyuzc9n9ppp924wqa8wcn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMnVINEp4ZGtCT2RxRzFU
            M0hPTUFTVCtvemIzSHZmb1RacHFjbjNndkhrCnQzRWdHNURPT3ZZTVhWRFJ3ZElj
            N0JoKzRaMVp1Nk5mdVpCcm5CSUp0RGMKLS0tIHhLWnpuSllmU3MycVNrK3ovQUJi
            VXIzVWlUQVVxVzdOQzBuR2Q0bTkzbHcKv1kISTAuNjxlDyiU8rVmWmNUUKhCKuO+
            ituQprVRY5ODQg3PhMGlixP/8KXDEuTx5zpBAT2pISju2cHyin1nDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T04:03:53Z"
    mac: ENC[AES256_GCM,data:OkkLNShIWstGPzeKJHOI6Uz+IpKTMJxZTpziLdV3vlmOgVKmyLCZnRsscrwZnyJmjrrSArAJTdjxLDLU16r070nTM8w75NT1OH7sTUu/zD5hrUbZkR8vQxjZ6HJXOIGz9fWSvXY/ZVSwVippAMlQKZLZj4M3Iyd2vATJlq09Nbo=,iv:49tw/UWQXps7f78e2TjZ3eKHRXlew/TGQxX76KLpSPc=,tag:HZuQnzkHEmRtQbMuAQuXSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
