apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5Ppu+/dqUVpqwdRL1LKIqTlfNkRIxh/Rk1FXTWElgbSHG+58,iv:5bAHC5l4vhtq0xa6r7MtsaDZiWCY2y/sa3xuIhN4UN0=,tag:PK8wgt/C9PdKG4Nxc0afgA==,type:str]
    credentials.json: ENC[AES256_GCM,data:w3+rsikE4GJOasxChcfx76hip6ou6oZRR89g9YEVVcLnh099tLD521AYAew3I3MJ120RnbbyfCQfIrZviufQurtybW8qnKpim93p6Nm4GXiAWH/kaL8D3UyweegQkSs/5e9Mgly1YGXdn12TYSsn6HVELqNUgvqGlkv8JdQWN+af9VXJ6woFQwyCm/ZmQAO/jhNq3WHSFlK+R3JFzIs2ZhHUq5ngD4pwivGPl5CgyQ==,iv:DFSp0sUmLCeVGoNvUayoA6/YPOBwvfybF2ucRkrgyGg=,tag:8LVdssJy745YCidplz94Gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t60uwv0pgk7fnsvn6g0wjrp2hpjsskcqlkgysyuzc9n9ppp924wqa8wcn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TXdkb0czTFlrZXNWQWY3
            TzVQcTlnU0lPMVE4QkVYR0tHOGxIQkpXMVR3ClpWbm9NMkhQdjUyakFCYzdqeUc4
            Y3diOWpRbFM3ZTBHeUd0UXAwTWNTYUkKLS0tIEMyZktNWEVlTXp0N0NWVCtCVFQv
            akVocU1EaEJLRU9nblhhbkhmUFhtNjAKf/MCFLQ0R7Ujb8uifA0rmNCJV1liqN5d
            KLG2F7WmMIX2KGHtz8CxSVQJH5+1jUviWTq1XRZqms0zU9nEyi4WPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T01:03:50Z"
    mac: ENC[AES256_GCM,data:eOHBTePnwn/b8W8FuzDH4DcFT8Ik6lDIELgk/16L3sqANSKAAImF1OH1KtRD2zj74IXN1Q65BIOyKzkJzcay+EEwgkT8x6rZgyqQ4M7pBAl+AAuaE0I4Y2s20VMj666q4RbcU8b46p5BbRUy/IFQlKfY+Kgo/o44eqKM0KbBwcM=,iv:MonM3fjo9eGMg5nGLoGJmxGmlPCddncGfgY0XjhEPvA=,tag:E3MU0NW5yq7ZAdiQrccL6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
