apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ZHmmgqUTCBACYhsjZuJrY1CHs/IHXFHRcmpa8MmusHw=,iv:GSDiJ/aIvSOvYkocKDs2aXWPVU/wlOMqjzcBCQQ9Jgs=,tag:Mfi/b8ewfLHmQ+sV+6Ne8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t60uwv0pgk7fnsvn6g0wjrp2hpjsskcqlkgysyuzc9n9ppp924wqa8wcn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMmxzeHFuTU5PanA1My8r
            SUV2OHA1U3MwaVBtN1Z2VDJsRkY3TytLZVVRCnByYkIzUC9jQ3pVN2dQMG0wVTIx
            R3c2MTR0QnVOZ1ZYamdTMmRsNmZtMXcKLS0tIFBoQkw4RllpMWVWTW5tdWhDeHps
            WXc2c2VBWlRLNkdWMlZJeWtOT1ZGZEkKqQd2xtdX6GpWPHXgDeLDiHMtu8DE5stb
            avWAYbBSWtb7XpqvaKDgLodbQ5ZbqJpSMaCBh10OIc/EQQr5vVMLyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T02:50:54Z"
    mac: ENC[AES256_GCM,data:OZ0fAZKkYTYjcdC0e57GvbfAH3AVn7XDNqt+Xl6lYbI/Uy6nV5if9cLKYDVMv/drG53ASMDmr0lnEdMdBQanijy/+7BqEKscKslZtMyVQqz8zgAwSszIDIYFMBtbDlO6ouYwEXv0qto3Qoln85s0pmhlkH/pcl/q6TpLKqmTK5Q=,iv:B6+BkTZECEu0Rejcv8uTRh/bedo4kCSpKhyNed7QhZk=,tag:+isAA6a0dXgDqDxJyZgnBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
